# Generated by Django 4.2.7 on 2025-08-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Label",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="연락처 분류용 라벨명 (예: 가족, 친구, 회사)",
                        max_length=50,
                        unique=True,
                        verbose_name="라벨명",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#007bff",
                        help_text="라벨 색상 (HEX 코드, 예: #FF0000",
                        max_length=7,
                        verbose_name="색상",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "라벨",
                "verbose_name_plural": "라벨",
                "db_table": "contract_label",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="연락처 이름 (필수)",
                        max_length=100,
                        verbose_name="이름",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="이메일 주소 (옵션)",
                        max_length=254,
                        null=True,
                        verbose_name="이메일",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="전화번호 (옵션)",
                        max_length=20,
                        null=True,
                        verbose_name="전화번호",
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True,
                        help_text="소속 회사명 (옵션)",
                        max_length=100,
                        null=True,
                        verbose_name="회사",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        help_text="회사 내 직책 (옵션)",
                        max_length=50,
                        null=True,
                        verbose_name="직책",
                    ),
                ),
                (
                    "memo",
                    models.TextField(
                        blank=True,
                        help_text="연락처 메모 (옵션)",
                        null=True,
                        verbose_name="메모",
                    ),
                ),
                (
                    "profile_url",
                    models.URLField(
                        blank=True,
                        help_text="프로필 사진 URL (옵션)",
                        null=True,
                        verbose_name="프로필 사진",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        help_text="주소 (옵션)",
                        max_length=200,
                        null=True,
                        verbose_name="주소",
                    ),
                ),
                (
                    "birthday",
                    models.DateField(
                        blank=True,
                        help_text="생년월일 (옵션)",
                        null=True,
                        verbose_name="생일",
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True,
                        help_text="웹사이트 URL (옵션)",
                        null=True,
                        verbose_name="웹사이트",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "labels",
                    models.ManyToManyField(
                        blank=True,
                        help_text="연락처 연결 라벨",
                        to="contacts.label",
                        verbose_name="라벨",
                    ),
                ),
            ],
            options={
                "verbose_name": "연락처",
                "verbose_name_plural": "연락처",
                "db_table": "contracts_contact",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["name"], name="idx_contact_name"),
                    models.Index(fields=["email"], name="idx_contact_email"),
                    models.Index(fields=["phone"], name="idx_contact_phone"),
                    models.Index(fields=["created_at"], name="idx_contact_created_at"),
                ],
            },
        ),
    ]
